### PR TITLE
Proper values in conf for PVC and latest tag

### PR DESCRIPTION
**Pull request by aureamunoz**
Related to #165

### CODE REVIEW

**Review by cmoulliard — COMMENTED** [review]
As we dont use what dekorate populates anymore, then I'm not sure that we should update the parameters and maybe they should be removed completely. WDYT ? @aureamunoz

**Comment by aureamunoz** [comment]
I needed them to deploy the bot and fix the problem about using the /z for mounting the database, so I think that it would be cool to align the configuration accordingly

**Comment by cmoulliard** [comment]
> I needed them to deploy the bot and fix the problem about using the /z for mounting the database

Why ? You can test a local deployment using the helm chart - https://github.com/snowdrop-bot/snowdrop-bot/tree/main/deploy/charts. No need to ask dekorate to generate the YAML resources as also defined part of the chart

**Comment by aureamunoz** [comment]
Because in prod the manifest for the bot didn't contain the volume and the image was pointing to /z. Once I removed /z from the config and image build Dockerfile, I needed to add the PVC to the manifest and apply it. As `helm` chart doesn't work in prod because of k8s version, I regenerated manifest with Quarkus extension (dekorate) and applied it by hand.

**Comment by aureamunoz** [comment]
As discussed, I removed the kubernetes specific configuration in favour of Helm chart @cmoulliard.

**Pull request closed without merging**
